/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.4 at Mon Feb 08 14:07:16 2016. */

#include "inotification.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Subscribe_request_response_fields[2] = {
    PB_FIELD(  1, UINT32  , REPEATED, CALLBACK, FIRST, Subscribe_request_response, FunctionID, FunctionID, 0),
    PB_LAST_FIELD
};

const pb_field_t Subscribe_response_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, Subscribe_response, FunctionResults, FunctionResults, &functionResults_fields),
    PB_LAST_FIELD
};

const pb_field_t RemoveSubscription_request_response_fields[2] = {
    PB_FIELD(  1, UINT32  , REPEATED, CALLBACK, FIRST, RemoveSubscription_request_response, FunctionID, FunctionID, 0),
    PB_LAST_FIELD
};

const pb_field_t RemoveSubscription_response_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, RemoveSubscription_response, FunctionResults, FunctionResults, &functionResults_fields),
    PB_LAST_FIELD
};

const pb_field_t functionResults_fields[3] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, functionResults, FunctionID, FunctionID, 0),
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , OTHER, functionResults, Successful, FunctionID, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Subscribe_response, FunctionResults) < 65536 && pb_membersize(RemoveSubscription_response, FunctionResults) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Subscribe_request_response_Subscribe_response_RemoveSubscription_request_response_RemoveSubscription_response_functionResults)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Subscribe_response, FunctionResults) < 256 && pb_membersize(RemoveSubscription_response, FunctionResults) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Subscribe_request_response_Subscribe_response_RemoveSubscription_request_response_RemoveSubscription_response_functionResults)
#endif


